plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
   # https://github.com/babel/eslint-plugin-babel
  - babel

env:
  jest: true
  node: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parser: babel-eslint

rules: 
  no-console: 0
